name: Container Scan
on:
  push:
    branches: [ container-scan ]
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: '1.8'  

jobs:
  CONTAINER_SCAN-BUILD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: Build with Maven
      run: mvn package --file pom.xml
      
    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Tag image
      run: |
        docker build -f ./Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/petclinic:${{ github.run_number }} .
   
    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ secrets.ACR_LOGIN_SERVER }}/petclinic:${{ github.run_number }}
        severity-threshold: CRITICAL
        run-quality-checks: true
        
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/petclinic:${{ github.run_number }}
